-- ==========================================================================
-- CLEANUP DE CANDIDATOS — Mantém apenas:
--   (1) candidatos do CSV inicial (categoria + subcategoria + nome)
--   (2) candidatos com origem = 'sugerido'
--   (3) candidatos que JÁ receberam pelo menos 1 voto
-- Deleta o restante (oficiais inventados/órfãos sem voto).
--
-- COMO USAR no Supabase SQL Editor:
--   Rode UMA query por vez (cada uma é auto-suficiente, com o CSV inline).
--     Q1 → resumo (quantos ficam, quantos saem)
--     Q2 → amostra do que será deletado
--     Q3 → linhas do CSV que NÃO bateram com nada (typo / subcategoria mudou)
--     Q4 → DELETE de verdade (só rode após validar Q1/Q2/Q3)
--
-- Sugeridos e candidatos com voto NUNCA são deletados (cláusulas do Q4).
-- ==========================================================================


-- ==========================================================================
-- Q1 — RESUMO (preview, não altera nada)
-- ==========================================================================
with csv_iniciais (categoria, subcategoria, nome) as (values
  ('Alimentação','Restaurante','Cariri Cabaña'),
  ('Alimentação','Restaurante','Terra Tupi'),
  ('Alimentação','Restaurante','Mangará'),
  ('Alimentação','Restaurante','Camarada Camarão'),
  ('Alimentação','Restaurante','Sal e Brasa'),
  ('Alimentação','Restaurante','Di Vino'),
  ('Alimentação','Restaurante','Carne de Sol do Ramiro'),
  ('Alimentação','Restaurante','Pitu com Pirão da Eliane'),
  ('Alimentação','Restaurante','Restaurante Sollo'),
  ('Alimentação','Restaurante','Porto Seaside'),
  ('Alimentação','Restaurante','Casa da Picanha'),
  ('Alimentação','Bar','Tarrafas'),
  ('Alimentação','Bar','Conversafiada'),
  ('Alimentação','Bar','Cantina Locatelli'),
  ('Alimentação','Bar','Passarela do Caranguejo'),
  ('Alimentação','Pizzaria','Santa Pizza'),
  ('Alimentação','Pizzaria','La Vecchia'),
  ('Alimentação','Pizzaria','Tarrafas'),
  ('Alimentação','Pizzaria','Conversafiada'),
  ('Alimentação','Pizzaria','Cantina Locatelli'),
  ('Alimentação','Hamburgueria','Rei do Hambúrguer'),
  ('Alimentação','Hamburgueria','La Brasa'),
  ('Alimentação','Hamburgueria','Original Gaúcho Burguer'),
  ('Alimentação','Hamburgueria','Hamburgueria Do Seu Zé'),
  ('Alimentação','Hamburgueria','The Sandwich'),
  ('Alimentação','Hamburgueria','Juca''s'),
  ('Alimentação','Hamburgueria','Sete Beijos'),
  ('Alimentação','Hamburgueria','Lion''s Burguer'),
  ('Alimentação','Hamburgueria','Oxente Hamburgueria'),
  ('Alimentação','Sushi','Japa Aju'),
  ('Alimentação','Sushi','Joy Sushi'),
  ('Alimentação','Sushi','New Hakata'),
  ('Alimentação','Acarajé','Acarajé do Marcelo'),
  ('Alimentação','Acarajé','Acarajé da Rita'),
  ('Alimentação','Acarajé','Rei do Acarajé Aju'),
  ('Alimentação','Acarajé','Ponto do Acarajé Coroa do Meio'),
  ('Alimentação','Padaria','Pães e Trigo'),
  ('Alimentação','Padaria','Regina Delicatessen'),
  ('Alimentação','Padaria','Pand''oro'),
  ('Alimentação','Padaria','Sorvepan'),
  ('Alimentação','Sorveteria','Castelo Branco'),
  ('Alimentação','Sorveteria','Il Sordo'),
  ('Alimentação','Sorveteria','Bonjour Gourmet'),
  ('Alimentação','Sorveteria','Trupe'),
  ('Alimentação','Sorveteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Feito a Grão'),
  ('Alimentação','Cafeteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Pand''oro'),
  ('Comércio','Loja de Roupas','Riachuelo'),
  ('Comércio','Loja de Roupas','C&A'),
  ('Comércio','Loja de Roupas','Renner'),
  ('Comércio','Loja de Roupas','Hering'),
  ('Comércio','Loja de Roupas','Aramis'),
  ('Comércio','Loja de Roupas','Damyller'),
  ('Comércio','Loja de Roupas','Les Lis Blanc'),
  ('Comércio','Loja de Roupas','Básico Chic Modas'),
  ('Comércio','Loja de Calçados','Arezzo'),
  ('Comércio','Loja de Calçados','Santa Lolla'),
  ('Comércio','Loja de Calçados','Schutz'),
  ('Comércio','Loja de Calçados','Paquetá'),
  ('Comércio','Ótica','Ótica Sunshine'),
  ('Comércio','Ótica','Super Ótica São José'),
  ('Comércio','Ótica','Óticas Kohls'),
  ('Comércio','Ótica','Ótica Sergipe'),
  ('Comércio','Ótica','Mercadão dos Óculos'),
  ('Comércio','Ótica','Óticas Pontual'),
  ('Comércio','Joalheria','Vivara'),
  ('Comércio','Joalheria','Joalheria Fontes'),
  ('Comércio','Joalheria','Karib Joias'),
  ('Comércio','Joalheria','Safira Jóias'),
  ('Comércio','Joalheria','Leonia Joias'),
  ('Comércio','Joalheria','Pandora'),
  ('Comércio','Farmácia','Pague Menos'),
  ('Comércio','Farmácia','Drogasil'),
  ('Comércio','Farmácia','Drogarias Pacheco'),
  ('Comércio','Farmácia','Ultrafarma'),
  ('Comércio','Supermercado','GBarbosa'),
  ('Comércio','Supermercado','Lojas Guanabara'),
  ('Comércio','Supermercado','Carrefour'),
  ('Comércio','Supermercado','Atacadão'),
  ('Comércio','Supermercado','Sam''s Club'),
  ('Comércio','Supermercado','Makro'),
  ('Comércio','Móveis','Lojas Guanabara'),
  ('Comércio','Móveis','Tok&Stok'),
  ('Comércio','Móveis','Etna'),
  ('Comércio','Decoração','Tok&Stok'),
  ('Comércio','Decoração','Etna'),
  ('Comércio','Decoração','Camicado'),
  ('Comércio','Eletrodomésticos','Lojas Guanabara'),
  ('Comércio','Eletrodomésticos','Magazine Luiza'),
  ('Comércio','Eletrodomésticos','Casas Bahia'),
  ('Comércio','Eletrodomésticos','Lojas Americanas'),
  ('Comércio','Celulares e acessórios','Magazine Luiza'),
  ('Comércio','Celulares e acessórios','Casas Bahia'),
  ('Comércio','Celulares e acessórios','Fast Shop'),
  ('Comércio','Informática','Magazine Luiza'),
  ('Comércio','Informática','Fast Shop'),
  ('Comércio','Informática','Kabum'),
  ('Comércio','Perfumarias','Essencial Perfumaria'),
  ('Comércio','Perfumarias','Lojão dos Cosméticos'),
  ('Comércio','Perfumarias','O Boticário'),
  ('Comércio','Perfumarias','Natura'),
  ('Comércio','Perfumarias','Sephora'),
  ('Comércio','Cosméticos','Essencial Perfumaria'),
  ('Comércio','Cosméticos','Lojão dos Cosméticos'),
  ('Comércio','Cosméticos','O Boticário'),
  ('Comércio','Cosméticos','Natura'),
  ('Comércio','Cama, mesa e banho','Lojas Imperador'),
  ('Comércio','Cama, mesa e banho','Demarque'),
  ('Comércio','Cama, mesa e banho','Sempre Viva'),
  ('Comércio','Cama, mesa e banho','Golfran Aracaju'),
  ('Comércio','Tecidos','Rei dos Tecidos'),
  ('Comércio','Armarinhos','Armarinho São José'),
  ('Comércio','Materiais de construção','Rede Oxente'),
  ('Comércio','Materiais de construção','Decora Construção'),
  ('Comércio','Materiais de construção','Edmundo Casa e Construção'),
  ('Serviços','Salão de Beleza','Lottus Saúde e Estética'),
  ('Serviços','Salão de Beleza','Aju Beauty Concept'),
  ('Serviços','Salão de Beleza','Maison Garcia'),
  ('Serviços','Salão de Beleza','EL Shamah'),
  ('Serviços','Barbearia','The Barbers'),
  ('Serviços','Barbearia','Maestro Barbearia'),
  ('Serviços','Barbearia','Castelo Barber Club'),
  ('Serviços','Barbearia','Aju Barber'),
  ('Serviços','Barbearia','Democrata Barber Club'),
  ('Serviços','Barbearia','Barbearia Dell Dú'),
  ('Serviços','Academia','Academia Total Fitness'),
  ('Serviços','Academia','Academia Força Física'),
  ('Serviços','Academia','Smith Academia'),
  ('Serviços','Academia','G3 Fit'),
  ('Serviços','Academia','Academia H2O Fitness'),
  ('Serviços','Academia','Academia Paulo Bedeu'),
  ('Serviços','Academia','Nossa Academia'),
  ('Serviços','Pet Shop','Cobasi'),
  ('Serviços','Pet Shop','Meupet'),
  ('Serviços','Pet Shop','PetMania'),
  ('Serviços','Pet Shop','Petville'),
  ('Serviços','Pet Shop','Univet'),
  ('Serviços','Organização de eventos','Wellington'),
  ('Serviços','Organização de eventos','Tina Delícias'),
  ('Serviços','Organização de eventos','Alex Max'),
  ('Serviços','Organização de eventos','Tânia Vasconcelos Buffet'),
  ('Serviços','Organização de eventos','Delícias na Brasa'),
  ('Serviços','Contabilidade e Consultoria','Zannix Brasil Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','MCE Menezes Contabilidade Empresarial'),
  ('Serviços','Contabilidade e Consultoria','ERPAC Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','INTERCON Contadores'),
  ('Serviços','Escritórios e Coworking','NEOWORKING'),
  ('Serviços','Escritórios e Coworking','Conviva Coworking'),
  ('Serviços','Escritórios e Coworking','HUA Coworking'),
  ('Serviços','Escritórios e Coworking','Ecoworking'),
  ('Serviços','Escritórios e Coworking','Top 360 Coworking'),
  ('Serviços','Escritórios e Coworking','Portal Escritório Virtual'),
  ('Lazer e Entretenimento','Casa de Show','Salles Multieventos'),
  ('Lazer e Entretenimento','Casa de Show','705 Aracaju'),
  ('Lazer e Entretenimento','Casa de Show','Amsterdam'),
  ('Lazer e Entretenimento','Casa de Show','Emes Centro de Eventos'),
  ('Lazer e Entretenimento','Cinema','Cinemark'),
  ('Lazer e Entretenimento','Cinema','UCI Cinemas'),
  ('Lazer e Entretenimento','Buffets','Wellington'),
  ('Lazer e Entretenimento','Buffets','Tina Delícias'),
  ('Lazer e Entretenimento','Buffets','Alex Max'),
  ('Lazer e Entretenimento','Buffets','Tânia Vasconcelos Buffet'),
  ('Lazer e Entretenimento','Hotéis','Celi Hotel'),
  ('Lazer e Entretenimento','Hotéis','Aquarius Praia Hotel'),
  ('Lazer e Entretenimento','Hotéis','Real Praia Hotel'),
  ('Lazer e Entretenimento','Pousadas','Hotel Pousada do Sol'),
  ('Lazer e Entretenimento','Pousadas','Pousada Dos Caminhos'),
  ('Lazer e Entretenimento','Pousadas','Pousada Raio de Sol'),
  ('Lazer e Entretenimento','Receptivos turísticos','Farol Tur'),
  ('Lazer e Entretenimento','Receptivos turísticos','Oxente Turismo'),
  ('Lazer e Entretenimento','Receptivos turísticos','Valtur Aracaju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Edsontur Viagens'),
  ('Lazer e Entretenimento','Receptivos turísticos','Receptivo Aju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Costa Nova Turismo'),
  ('Educação','Escolas','Colégio CCPA'),
  ('Educação','Escolas','Colégio Intellectus'),
  ('Educação','Escolas','Colégio Ômega'),
  ('Educação','Escolas','Colégio Pio Décimo'),
  ('Educação','Escolas','Colégio Salesiano Aracaju'),
  ('Educação','Escolas','Instituto Dom Fernando Gomes'),
  ('Educação','Idiomas','Cultura Inglesa'),
  ('Educação','Idiomas','CCAA'),
  ('Educação','Idiomas','Wizard'),
  ('Educação','Idiomas','Yázigi'),
  ('Educação','Cursos livres','SENAC'),
  ('Educação','Cursos livres','SENAI'),
  ('Educação','Cursos livres','Universidade Tiradentes (Unit)'),
  ('Educação','Cursos livres','Uninassau'),
  ('Educação','Cursos livres','FACAR'),
  ('Educação','Cursos livres','Estácio (UNESA)'),
  ('Imóveis e Construção','Construtora','Jotanunes'),
  ('Imóveis e Construção','Construtora','Construtora Impacto'),
  ('Imóveis e Construção','Construtora','Construtora União'),
  ('Imóveis e Construção','Construtora','Construtora KLB'),
  ('Imóveis e Construção','Construtora','Construtora Stanza'),
  ('Imóveis e Construção','Construtora','Construtora Santa Maria'),
  ('Imóveis e Construção','Construtora','GL Construtora'),
  ('Imóveis e Construção','Construtora','Construtora EMPE'),
  ('Imóveis e Construção','Imobiliária','Gonzalez Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Cohab Premium'),
  ('Imóveis e Construção','Imobiliária','Smart Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Felizola Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Valor Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Monica Andrade Imóveis'),
  ('Saúde','Hospital','Hospital Primavera'),
  ('Saúde','Hospital','Hospital São Lucas'),
  ('Saúde','Hospital','Hospital Hapvida'),
  ('Saúde','Clínica Veterinária','Univet'),
  ('Saúde','Clínica Veterinária','Afetto'),
  ('Saúde','Clínica Veterinária','Clínica São Lázaro'),
  ('Saúde','Clínica Veterinária','Diagnovet'),
  ('Saúde','Clínica Veterinária','Toca dos Gatos'),
  ('Saúde','Clínica Veterinária','Mr. Zoo'),
  ('Saúde','Plano de Saúde','Hapvida'),
  ('Saúde','Plano de Saúde','Unimed Sergipe'),
  ('Saúde','Plano de Saúde','Bradesco Saúde'),
  ('Saúde','Plano de Saúde','Amil'),
  ('Saúde','Laboratório','Centro de Diagnóstico Unimed'),
  ('Saúde','Laboratório','Lamac'),
  ('Saúde','Laboratório','Solim Laboratórios'),
  ('Saúde','Laboratório','Santa Anna'),
  ('Automotivo','Concessionária','Serigy Veículos'),
  ('Automotivo','Concessionária','Samam Fiat'),
  ('Automotivo','Concessionária','Chevrolet Contorno'),
  ('Automotivo','Auto Peças','O Barateiro Auto Peças'),
  ('Automotivo','Auto Peças','Auto Peças Macedo'),
  ('Automotivo','Auto Peças','Auto Peças Cardoso'),
  ('Automotivo','Auto Peças','JS Peças'),
  ('Automotivo','Auto Peças','Silveira Auto Peças'),
  ('Automotivo','Mecânica','AK Auto Center')
),
decisao as (
  select
    case
      when exists (
        select 1 from csv_iniciais csv
        where lower(trim(csv.nome)) = lower(trim(c.nome))
          and lower(trim(csv.subcategoria)) = lower(trim(s.nome))
          and lower(trim(csv.categoria)) = lower(trim(cat.nome))
      ) then 'manter:csv'
      when c.origem = 'sugerido' then 'manter:sugerido'
      when exists (select 1 from votos v where v.candidato_id = c.id) then 'manter:votado'
      else 'DELETAR'
    end as decisao
  from candidatos c
  join subcategorias s on s.id = c.subcategoria_id
  join categorias cat on cat.id = s.categoria_id
)
select decisao, count(*) as total
from decisao
group by decisao
order by decisao;


-- ==========================================================================
-- Q2 — AMOSTRA do que será deletado (até 200 linhas)
-- ==========================================================================
with csv_iniciais (categoria, subcategoria, nome) as (values
  ('Alimentação','Restaurante','Cariri Cabaña'),
  ('Alimentação','Restaurante','Terra Tupi'),
  ('Alimentação','Restaurante','Mangará'),
  ('Alimentação','Restaurante','Camarada Camarão'),
  ('Alimentação','Restaurante','Sal e Brasa'),
  ('Alimentação','Restaurante','Di Vino'),
  ('Alimentação','Restaurante','Carne de Sol do Ramiro'),
  ('Alimentação','Restaurante','Pitu com Pirão da Eliane'),
  ('Alimentação','Restaurante','Restaurante Sollo'),
  ('Alimentação','Restaurante','Porto Seaside'),
  ('Alimentação','Restaurante','Casa da Picanha'),
  ('Alimentação','Bar','Tarrafas'),
  ('Alimentação','Bar','Conversafiada'),
  ('Alimentação','Bar','Cantina Locatelli'),
  ('Alimentação','Bar','Passarela do Caranguejo'),
  ('Alimentação','Pizzaria','Santa Pizza'),
  ('Alimentação','Pizzaria','La Vecchia'),
  ('Alimentação','Pizzaria','Tarrafas'),
  ('Alimentação','Pizzaria','Conversafiada'),
  ('Alimentação','Pizzaria','Cantina Locatelli'),
  ('Alimentação','Hamburgueria','Rei do Hambúrguer'),
  ('Alimentação','Hamburgueria','La Brasa'),
  ('Alimentação','Hamburgueria','Original Gaúcho Burguer'),
  ('Alimentação','Hamburgueria','Hamburgueria Do Seu Zé'),
  ('Alimentação','Hamburgueria','The Sandwich'),
  ('Alimentação','Hamburgueria','Juca''s'),
  ('Alimentação','Hamburgueria','Sete Beijos'),
  ('Alimentação','Hamburgueria','Lion''s Burguer'),
  ('Alimentação','Hamburgueria','Oxente Hamburgueria'),
  ('Alimentação','Sushi','Japa Aju'),
  ('Alimentação','Sushi','Joy Sushi'),
  ('Alimentação','Sushi','New Hakata'),
  ('Alimentação','Acarajé','Acarajé do Marcelo'),
  ('Alimentação','Acarajé','Acarajé da Rita'),
  ('Alimentação','Acarajé','Rei do Acarajé Aju'),
  ('Alimentação','Acarajé','Ponto do Acarajé Coroa do Meio'),
  ('Alimentação','Padaria','Pães e Trigo'),
  ('Alimentação','Padaria','Regina Delicatessen'),
  ('Alimentação','Padaria','Pand''oro'),
  ('Alimentação','Padaria','Sorvepan'),
  ('Alimentação','Sorveteria','Castelo Branco'),
  ('Alimentação','Sorveteria','Il Sordo'),
  ('Alimentação','Sorveteria','Bonjour Gourmet'),
  ('Alimentação','Sorveteria','Trupe'),
  ('Alimentação','Sorveteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Feito a Grão'),
  ('Alimentação','Cafeteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Pand''oro'),
  ('Comércio','Loja de Roupas','Riachuelo'),
  ('Comércio','Loja de Roupas','C&A'),
  ('Comércio','Loja de Roupas','Renner'),
  ('Comércio','Loja de Roupas','Hering'),
  ('Comércio','Loja de Roupas','Aramis'),
  ('Comércio','Loja de Roupas','Damyller'),
  ('Comércio','Loja de Roupas','Les Lis Blanc'),
  ('Comércio','Loja de Roupas','Básico Chic Modas'),
  ('Comércio','Loja de Calçados','Arezzo'),
  ('Comércio','Loja de Calçados','Santa Lolla'),
  ('Comércio','Loja de Calçados','Schutz'),
  ('Comércio','Loja de Calçados','Paquetá'),
  ('Comércio','Ótica','Ótica Sunshine'),
  ('Comércio','Ótica','Super Ótica São José'),
  ('Comércio','Ótica','Óticas Kohls'),
  ('Comércio','Ótica','Ótica Sergipe'),
  ('Comércio','Ótica','Mercadão dos Óculos'),
  ('Comércio','Ótica','Óticas Pontual'),
  ('Comércio','Joalheria','Vivara'),
  ('Comércio','Joalheria','Joalheria Fontes'),
  ('Comércio','Joalheria','Karib Joias'),
  ('Comércio','Joalheria','Safira Jóias'),
  ('Comércio','Joalheria','Leonia Joias'),
  ('Comércio','Joalheria','Pandora'),
  ('Comércio','Farmácia','Pague Menos'),
  ('Comércio','Farmácia','Drogasil'),
  ('Comércio','Farmácia','Drogarias Pacheco'),
  ('Comércio','Farmácia','Ultrafarma'),
  ('Comércio','Supermercado','GBarbosa'),
  ('Comércio','Supermercado','Lojas Guanabara'),
  ('Comércio','Supermercado','Carrefour'),
  ('Comércio','Supermercado','Atacadão'),
  ('Comércio','Supermercado','Sam''s Club'),
  ('Comércio','Supermercado','Makro'),
  ('Comércio','Móveis','Lojas Guanabara'),
  ('Comércio','Móveis','Tok&Stok'),
  ('Comércio','Móveis','Etna'),
  ('Comércio','Decoração','Tok&Stok'),
  ('Comércio','Decoração','Etna'),
  ('Comércio','Decoração','Camicado'),
  ('Comércio','Eletrodomésticos','Lojas Guanabara'),
  ('Comércio','Eletrodomésticos','Magazine Luiza'),
  ('Comércio','Eletrodomésticos','Casas Bahia'),
  ('Comércio','Eletrodomésticos','Lojas Americanas'),
  ('Comércio','Celulares e acessórios','Magazine Luiza'),
  ('Comércio','Celulares e acessórios','Casas Bahia'),
  ('Comércio','Celulares e acessórios','Fast Shop'),
  ('Comércio','Informática','Magazine Luiza'),
  ('Comércio','Informática','Fast Shop'),
  ('Comércio','Informática','Kabum'),
  ('Comércio','Perfumarias','Essencial Perfumaria'),
  ('Comércio','Perfumarias','Lojão dos Cosméticos'),
  ('Comércio','Perfumarias','O Boticário'),
  ('Comércio','Perfumarias','Natura'),
  ('Comércio','Perfumarias','Sephora'),
  ('Comércio','Cosméticos','Essencial Perfumaria'),
  ('Comércio','Cosméticos','Lojão dos Cosméticos'),
  ('Comércio','Cosméticos','O Boticário'),
  ('Comércio','Cosméticos','Natura'),
  ('Comércio','Cama, mesa e banho','Lojas Imperador'),
  ('Comércio','Cama, mesa e banho','Demarque'),
  ('Comércio','Cama, mesa e banho','Sempre Viva'),
  ('Comércio','Cama, mesa e banho','Golfran Aracaju'),
  ('Comércio','Tecidos','Rei dos Tecidos'),
  ('Comércio','Armarinhos','Armarinho São José'),
  ('Comércio','Materiais de construção','Rede Oxente'),
  ('Comércio','Materiais de construção','Decora Construção'),
  ('Comércio','Materiais de construção','Edmundo Casa e Construção'),
  ('Serviços','Salão de Beleza','Lottus Saúde e Estética'),
  ('Serviços','Salão de Beleza','Aju Beauty Concept'),
  ('Serviços','Salão de Beleza','Maison Garcia'),
  ('Serviços','Salão de Beleza','EL Shamah'),
  ('Serviços','Barbearia','The Barbers'),
  ('Serviços','Barbearia','Maestro Barbearia'),
  ('Serviços','Barbearia','Castelo Barber Club'),
  ('Serviços','Barbearia','Aju Barber'),
  ('Serviços','Barbearia','Democrata Barber Club'),
  ('Serviços','Barbearia','Barbearia Dell Dú'),
  ('Serviços','Academia','Academia Total Fitness'),
  ('Serviços','Academia','Academia Força Física'),
  ('Serviços','Academia','Smith Academia'),
  ('Serviços','Academia','G3 Fit'),
  ('Serviços','Academia','Academia H2O Fitness'),
  ('Serviços','Academia','Academia Paulo Bedeu'),
  ('Serviços','Academia','Nossa Academia'),
  ('Serviços','Pet Shop','Cobasi'),
  ('Serviços','Pet Shop','Meupet'),
  ('Serviços','Pet Shop','PetMania'),
  ('Serviços','Pet Shop','Petville'),
  ('Serviços','Pet Shop','Univet'),
  ('Serviços','Organização de eventos','Wellington'),
  ('Serviços','Organização de eventos','Tina Delícias'),
  ('Serviços','Organização de eventos','Alex Max'),
  ('Serviços','Organização de eventos','Tânia Vasconcelos Buffet'),
  ('Serviços','Organização de eventos','Delícias na Brasa'),
  ('Serviços','Contabilidade e Consultoria','Zannix Brasil Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','MCE Menezes Contabilidade Empresarial'),
  ('Serviços','Contabilidade e Consultoria','ERPAC Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','INTERCON Contadores'),
  ('Serviços','Escritórios e Coworking','NEOWORKING'),
  ('Serviços','Escritórios e Coworking','Conviva Coworking'),
  ('Serviços','Escritórios e Coworking','HUA Coworking'),
  ('Serviços','Escritórios e Coworking','Ecoworking'),
  ('Serviços','Escritórios e Coworking','Top 360 Coworking'),
  ('Serviços','Escritórios e Coworking','Portal Escritório Virtual'),
  ('Lazer e Entretenimento','Casa de Show','Salles Multieventos'),
  ('Lazer e Entretenimento','Casa de Show','705 Aracaju'),
  ('Lazer e Entretenimento','Casa de Show','Amsterdam'),
  ('Lazer e Entretenimento','Casa de Show','Emes Centro de Eventos'),
  ('Lazer e Entretenimento','Cinema','Cinemark'),
  ('Lazer e Entretenimento','Cinema','UCI Cinemas'),
  ('Lazer e Entretenimento','Buffets','Wellington'),
  ('Lazer e Entretenimento','Buffets','Tina Delícias'),
  ('Lazer e Entretenimento','Buffets','Alex Max'),
  ('Lazer e Entretenimento','Buffets','Tânia Vasconcelos Buffet'),
  ('Lazer e Entretenimento','Hotéis','Celi Hotel'),
  ('Lazer e Entretenimento','Hotéis','Aquarius Praia Hotel'),
  ('Lazer e Entretenimento','Hotéis','Real Praia Hotel'),
  ('Lazer e Entretenimento','Pousadas','Hotel Pousada do Sol'),
  ('Lazer e Entretenimento','Pousadas','Pousada Dos Caminhos'),
  ('Lazer e Entretenimento','Pousadas','Pousada Raio de Sol'),
  ('Lazer e Entretenimento','Receptivos turísticos','Farol Tur'),
  ('Lazer e Entretenimento','Receptivos turísticos','Oxente Turismo'),
  ('Lazer e Entretenimento','Receptivos turísticos','Valtur Aracaju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Edsontur Viagens'),
  ('Lazer e Entretenimento','Receptivos turísticos','Receptivo Aju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Costa Nova Turismo'),
  ('Educação','Escolas','Colégio CCPA'),
  ('Educação','Escolas','Colégio Intellectus'),
  ('Educação','Escolas','Colégio Ômega'),
  ('Educação','Escolas','Colégio Pio Décimo'),
  ('Educação','Escolas','Colégio Salesiano Aracaju'),
  ('Educação','Escolas','Instituto Dom Fernando Gomes'),
  ('Educação','Idiomas','Cultura Inglesa'),
  ('Educação','Idiomas','CCAA'),
  ('Educação','Idiomas','Wizard'),
  ('Educação','Idiomas','Yázigi'),
  ('Educação','Cursos livres','SENAC'),
  ('Educação','Cursos livres','SENAI'),
  ('Educação','Cursos livres','Universidade Tiradentes (Unit)'),
  ('Educação','Cursos livres','Uninassau'),
  ('Educação','Cursos livres','FACAR'),
  ('Educação','Cursos livres','Estácio (UNESA)'),
  ('Imóveis e Construção','Construtora','Jotanunes'),
  ('Imóveis e Construção','Construtora','Construtora Impacto'),
  ('Imóveis e Construção','Construtora','Construtora União'),
  ('Imóveis e Construção','Construtora','Construtora KLB'),
  ('Imóveis e Construção','Construtora','Construtora Stanza'),
  ('Imóveis e Construção','Construtora','Construtora Santa Maria'),
  ('Imóveis e Construção','Construtora','GL Construtora'),
  ('Imóveis e Construção','Construtora','Construtora EMPE'),
  ('Imóveis e Construção','Imobiliária','Gonzalez Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Cohab Premium'),
  ('Imóveis e Construção','Imobiliária','Smart Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Felizola Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Valor Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Monica Andrade Imóveis'),
  ('Saúde','Hospital','Hospital Primavera'),
  ('Saúde','Hospital','Hospital São Lucas'),
  ('Saúde','Hospital','Hospital Hapvida'),
  ('Saúde','Clínica Veterinária','Univet'),
  ('Saúde','Clínica Veterinária','Afetto'),
  ('Saúde','Clínica Veterinária','Clínica São Lázaro'),
  ('Saúde','Clínica Veterinária','Diagnovet'),
  ('Saúde','Clínica Veterinária','Toca dos Gatos'),
  ('Saúde','Clínica Veterinária','Mr. Zoo'),
  ('Saúde','Plano de Saúde','Hapvida'),
  ('Saúde','Plano de Saúde','Unimed Sergipe'),
  ('Saúde','Plano de Saúde','Bradesco Saúde'),
  ('Saúde','Plano de Saúde','Amil'),
  ('Saúde','Laboratório','Centro de Diagnóstico Unimed'),
  ('Saúde','Laboratório','Lamac'),
  ('Saúde','Laboratório','Solim Laboratórios'),
  ('Saúde','Laboratório','Santa Anna'),
  ('Automotivo','Concessionária','Serigy Veículos'),
  ('Automotivo','Concessionária','Samam Fiat'),
  ('Automotivo','Concessionária','Chevrolet Contorno'),
  ('Automotivo','Auto Peças','O Barateiro Auto Peças'),
  ('Automotivo','Auto Peças','Auto Peças Macedo'),
  ('Automotivo','Auto Peças','Auto Peças Cardoso'),
  ('Automotivo','Auto Peças','JS Peças'),
  ('Automotivo','Auto Peças','Silveira Auto Peças'),
  ('Automotivo','Mecânica','AK Auto Center')
)
select cat.nome as categoria, s.nome as subcategoria, c.nome
from candidatos c
join subcategorias s on s.id = c.subcategoria_id
join categorias cat on cat.id = s.categoria_id
where c.origem = 'oficial'
  and not exists (
    select 1 from csv_iniciais csv
    where lower(trim(csv.nome)) = lower(trim(c.nome))
      and lower(trim(csv.subcategoria)) = lower(trim(s.nome))
      and lower(trim(csv.categoria)) = lower(trim(cat.nome))
  )
  and not exists (select 1 from votos v where v.candidato_id = c.id)
order by cat.nome, s.nome, c.nome
limit 200;


-- ==========================================================================
-- Q3 — Linhas do CSV que NÃO bateram com nada no banco
-- (subcategoria não existe, ou nome com grafia diferente)
-- ==========================================================================
with csv_iniciais (categoria, subcategoria, nome) as (values
  ('Alimentação','Restaurante','Cariri Cabaña'),
  ('Alimentação','Restaurante','Terra Tupi'),
  ('Alimentação','Restaurante','Mangará'),
  ('Alimentação','Restaurante','Camarada Camarão'),
  ('Alimentação','Restaurante','Sal e Brasa'),
  ('Alimentação','Restaurante','Di Vino'),
  ('Alimentação','Restaurante','Carne de Sol do Ramiro'),
  ('Alimentação','Restaurante','Pitu com Pirão da Eliane'),
  ('Alimentação','Restaurante','Restaurante Sollo'),
  ('Alimentação','Restaurante','Porto Seaside'),
  ('Alimentação','Restaurante','Casa da Picanha'),
  ('Alimentação','Bar','Tarrafas'),
  ('Alimentação','Bar','Conversafiada'),
  ('Alimentação','Bar','Cantina Locatelli'),
  ('Alimentação','Bar','Passarela do Caranguejo'),
  ('Alimentação','Pizzaria','Santa Pizza'),
  ('Alimentação','Pizzaria','La Vecchia'),
  ('Alimentação','Pizzaria','Tarrafas'),
  ('Alimentação','Pizzaria','Conversafiada'),
  ('Alimentação','Pizzaria','Cantina Locatelli'),
  ('Alimentação','Hamburgueria','Rei do Hambúrguer'),
  ('Alimentação','Hamburgueria','La Brasa'),
  ('Alimentação','Hamburgueria','Original Gaúcho Burguer'),
  ('Alimentação','Hamburgueria','Hamburgueria Do Seu Zé'),
  ('Alimentação','Hamburgueria','The Sandwich'),
  ('Alimentação','Hamburgueria','Juca''s'),
  ('Alimentação','Hamburgueria','Sete Beijos'),
  ('Alimentação','Hamburgueria','Lion''s Burguer'),
  ('Alimentação','Hamburgueria','Oxente Hamburgueria'),
  ('Alimentação','Sushi','Japa Aju'),
  ('Alimentação','Sushi','Joy Sushi'),
  ('Alimentação','Sushi','New Hakata'),
  ('Alimentação','Acarajé','Acarajé do Marcelo'),
  ('Alimentação','Acarajé','Acarajé da Rita'),
  ('Alimentação','Acarajé','Rei do Acarajé Aju'),
  ('Alimentação','Acarajé','Ponto do Acarajé Coroa do Meio'),
  ('Alimentação','Padaria','Pães e Trigo'),
  ('Alimentação','Padaria','Regina Delicatessen'),
  ('Alimentação','Padaria','Pand''oro'),
  ('Alimentação','Padaria','Sorvepan'),
  ('Alimentação','Sorveteria','Castelo Branco'),
  ('Alimentação','Sorveteria','Il Sordo'),
  ('Alimentação','Sorveteria','Bonjour Gourmet'),
  ('Alimentação','Sorveteria','Trupe'),
  ('Alimentação','Sorveteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Feito a Grão'),
  ('Alimentação','Cafeteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Pand''oro'),
  ('Comércio','Loja de Roupas','Riachuelo'),
  ('Comércio','Loja de Roupas','C&A'),
  ('Comércio','Loja de Roupas','Renner'),
  ('Comércio','Loja de Roupas','Hering'),
  ('Comércio','Loja de Roupas','Aramis'),
  ('Comércio','Loja de Roupas','Damyller'),
  ('Comércio','Loja de Roupas','Les Lis Blanc'),
  ('Comércio','Loja de Roupas','Básico Chic Modas'),
  ('Comércio','Loja de Calçados','Arezzo'),
  ('Comércio','Loja de Calçados','Santa Lolla'),
  ('Comércio','Loja de Calçados','Schutz'),
  ('Comércio','Loja de Calçados','Paquetá'),
  ('Comércio','Ótica','Ótica Sunshine'),
  ('Comércio','Ótica','Super Ótica São José'),
  ('Comércio','Ótica','Óticas Kohls'),
  ('Comércio','Ótica','Ótica Sergipe'),
  ('Comércio','Ótica','Mercadão dos Óculos'),
  ('Comércio','Ótica','Óticas Pontual'),
  ('Comércio','Joalheria','Vivara'),
  ('Comércio','Joalheria','Joalheria Fontes'),
  ('Comércio','Joalheria','Karib Joias'),
  ('Comércio','Joalheria','Safira Jóias'),
  ('Comércio','Joalheria','Leonia Joias'),
  ('Comércio','Joalheria','Pandora'),
  ('Comércio','Farmácia','Pague Menos'),
  ('Comércio','Farmácia','Drogasil'),
  ('Comércio','Farmácia','Drogarias Pacheco'),
  ('Comércio','Farmácia','Ultrafarma'),
  ('Comércio','Supermercado','GBarbosa'),
  ('Comércio','Supermercado','Lojas Guanabara'),
  ('Comércio','Supermercado','Carrefour'),
  ('Comércio','Supermercado','Atacadão'),
  ('Comércio','Supermercado','Sam''s Club'),
  ('Comércio','Supermercado','Makro'),
  ('Comércio','Móveis','Lojas Guanabara'),
  ('Comércio','Móveis','Tok&Stok'),
  ('Comércio','Móveis','Etna'),
  ('Comércio','Decoração','Tok&Stok'),
  ('Comércio','Decoração','Etna'),
  ('Comércio','Decoração','Camicado'),
  ('Comércio','Eletrodomésticos','Lojas Guanabara'),
  ('Comércio','Eletrodomésticos','Magazine Luiza'),
  ('Comércio','Eletrodomésticos','Casas Bahia'),
  ('Comércio','Eletrodomésticos','Lojas Americanas'),
  ('Comércio','Celulares e acessórios','Magazine Luiza'),
  ('Comércio','Celulares e acessórios','Casas Bahia'),
  ('Comércio','Celulares e acessórios','Fast Shop'),
  ('Comércio','Informática','Magazine Luiza'),
  ('Comércio','Informática','Fast Shop'),
  ('Comércio','Informática','Kabum'),
  ('Comércio','Perfumarias','Essencial Perfumaria'),
  ('Comércio','Perfumarias','Lojão dos Cosméticos'),
  ('Comércio','Perfumarias','O Boticário'),
  ('Comércio','Perfumarias','Natura'),
  ('Comércio','Perfumarias','Sephora'),
  ('Comércio','Cosméticos','Essencial Perfumaria'),
  ('Comércio','Cosméticos','Lojão dos Cosméticos'),
  ('Comércio','Cosméticos','O Boticário'),
  ('Comércio','Cosméticos','Natura'),
  ('Comércio','Cama, mesa e banho','Lojas Imperador'),
  ('Comércio','Cama, mesa e banho','Demarque'),
  ('Comércio','Cama, mesa e banho','Sempre Viva'),
  ('Comércio','Cama, mesa e banho','Golfran Aracaju'),
  ('Comércio','Tecidos','Rei dos Tecidos'),
  ('Comércio','Armarinhos','Armarinho São José'),
  ('Comércio','Materiais de construção','Rede Oxente'),
  ('Comércio','Materiais de construção','Decora Construção'),
  ('Comércio','Materiais de construção','Edmundo Casa e Construção'),
  ('Serviços','Salão de Beleza','Lottus Saúde e Estética'),
  ('Serviços','Salão de Beleza','Aju Beauty Concept'),
  ('Serviços','Salão de Beleza','Maison Garcia'),
  ('Serviços','Salão de Beleza','EL Shamah'),
  ('Serviços','Barbearia','The Barbers'),
  ('Serviços','Barbearia','Maestro Barbearia'),
  ('Serviços','Barbearia','Castelo Barber Club'),
  ('Serviços','Barbearia','Aju Barber'),
  ('Serviços','Barbearia','Democrata Barber Club'),
  ('Serviços','Barbearia','Barbearia Dell Dú'),
  ('Serviços','Academia','Academia Total Fitness'),
  ('Serviços','Academia','Academia Força Física'),
  ('Serviços','Academia','Smith Academia'),
  ('Serviços','Academia','G3 Fit'),
  ('Serviços','Academia','Academia H2O Fitness'),
  ('Serviços','Academia','Academia Paulo Bedeu'),
  ('Serviços','Academia','Nossa Academia'),
  ('Serviços','Pet Shop','Cobasi'),
  ('Serviços','Pet Shop','Meupet'),
  ('Serviços','Pet Shop','PetMania'),
  ('Serviços','Pet Shop','Petville'),
  ('Serviços','Pet Shop','Univet'),
  ('Serviços','Organização de eventos','Wellington'),
  ('Serviços','Organização de eventos','Tina Delícias'),
  ('Serviços','Organização de eventos','Alex Max'),
  ('Serviços','Organização de eventos','Tânia Vasconcelos Buffet'),
  ('Serviços','Organização de eventos','Delícias na Brasa'),
  ('Serviços','Contabilidade e Consultoria','Zannix Brasil Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','MCE Menezes Contabilidade Empresarial'),
  ('Serviços','Contabilidade e Consultoria','ERPAC Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','INTERCON Contadores'),
  ('Serviços','Escritórios e Coworking','NEOWORKING'),
  ('Serviços','Escritórios e Coworking','Conviva Coworking'),
  ('Serviços','Escritórios e Coworking','HUA Coworking'),
  ('Serviços','Escritórios e Coworking','Ecoworking'),
  ('Serviços','Escritórios e Coworking','Top 360 Coworking'),
  ('Serviços','Escritórios e Coworking','Portal Escritório Virtual'),
  ('Lazer e Entretenimento','Casa de Show','Salles Multieventos'),
  ('Lazer e Entretenimento','Casa de Show','705 Aracaju'),
  ('Lazer e Entretenimento','Casa de Show','Amsterdam'),
  ('Lazer e Entretenimento','Casa de Show','Emes Centro de Eventos'),
  ('Lazer e Entretenimento','Cinema','Cinemark'),
  ('Lazer e Entretenimento','Cinema','UCI Cinemas'),
  ('Lazer e Entretenimento','Buffets','Wellington'),
  ('Lazer e Entretenimento','Buffets','Tina Delícias'),
  ('Lazer e Entretenimento','Buffets','Alex Max'),
  ('Lazer e Entretenimento','Buffets','Tânia Vasconcelos Buffet'),
  ('Lazer e Entretenimento','Hotéis','Celi Hotel'),
  ('Lazer e Entretenimento','Hotéis','Aquarius Praia Hotel'),
  ('Lazer e Entretenimento','Hotéis','Real Praia Hotel'),
  ('Lazer e Entretenimento','Pousadas','Hotel Pousada do Sol'),
  ('Lazer e Entretenimento','Pousadas','Pousada Dos Caminhos'),
  ('Lazer e Entretenimento','Pousadas','Pousada Raio de Sol'),
  ('Lazer e Entretenimento','Receptivos turísticos','Farol Tur'),
  ('Lazer e Entretenimento','Receptivos turísticos','Oxente Turismo'),
  ('Lazer e Entretenimento','Receptivos turísticos','Valtur Aracaju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Edsontur Viagens'),
  ('Lazer e Entretenimento','Receptivos turísticos','Receptivo Aju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Costa Nova Turismo'),
  ('Educação','Escolas','Colégio CCPA'),
  ('Educação','Escolas','Colégio Intellectus'),
  ('Educação','Escolas','Colégio Ômega'),
  ('Educação','Escolas','Colégio Pio Décimo'),
  ('Educação','Escolas','Colégio Salesiano Aracaju'),
  ('Educação','Escolas','Instituto Dom Fernando Gomes'),
  ('Educação','Idiomas','Cultura Inglesa'),
  ('Educação','Idiomas','CCAA'),
  ('Educação','Idiomas','Wizard'),
  ('Educação','Idiomas','Yázigi'),
  ('Educação','Cursos livres','SENAC'),
  ('Educação','Cursos livres','SENAI'),
  ('Educação','Cursos livres','Universidade Tiradentes (Unit)'),
  ('Educação','Cursos livres','Uninassau'),
  ('Educação','Cursos livres','FACAR'),
  ('Educação','Cursos livres','Estácio (UNESA)'),
  ('Imóveis e Construção','Construtora','Jotanunes'),
  ('Imóveis e Construção','Construtora','Construtora Impacto'),
  ('Imóveis e Construção','Construtora','Construtora União'),
  ('Imóveis e Construção','Construtora','Construtora KLB'),
  ('Imóveis e Construção','Construtora','Construtora Stanza'),
  ('Imóveis e Construção','Construtora','Construtora Santa Maria'),
  ('Imóveis e Construção','Construtora','GL Construtora'),
  ('Imóveis e Construção','Construtora','Construtora EMPE'),
  ('Imóveis e Construção','Imobiliária','Gonzalez Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Cohab Premium'),
  ('Imóveis e Construção','Imobiliária','Smart Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Felizola Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Valor Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Monica Andrade Imóveis'),
  ('Saúde','Hospital','Hospital Primavera'),
  ('Saúde','Hospital','Hospital São Lucas'),
  ('Saúde','Hospital','Hospital Hapvida'),
  ('Saúde','Clínica Veterinária','Univet'),
  ('Saúde','Clínica Veterinária','Afetto'),
  ('Saúde','Clínica Veterinária','Clínica São Lázaro'),
  ('Saúde','Clínica Veterinária','Diagnovet'),
  ('Saúde','Clínica Veterinária','Toca dos Gatos'),
  ('Saúde','Clínica Veterinária','Mr. Zoo'),
  ('Saúde','Plano de Saúde','Hapvida'),
  ('Saúde','Plano de Saúde','Unimed Sergipe'),
  ('Saúde','Plano de Saúde','Bradesco Saúde'),
  ('Saúde','Plano de Saúde','Amil'),
  ('Saúde','Laboratório','Centro de Diagnóstico Unimed'),
  ('Saúde','Laboratório','Lamac'),
  ('Saúde','Laboratório','Solim Laboratórios'),
  ('Saúde','Laboratório','Santa Anna'),
  ('Automotivo','Concessionária','Serigy Veículos'),
  ('Automotivo','Concessionária','Samam Fiat'),
  ('Automotivo','Concessionária','Chevrolet Contorno'),
  ('Automotivo','Auto Peças','O Barateiro Auto Peças'),
  ('Automotivo','Auto Peças','Auto Peças Macedo'),
  ('Automotivo','Auto Peças','Auto Peças Cardoso'),
  ('Automotivo','Auto Peças','JS Peças'),
  ('Automotivo','Auto Peças','Silveira Auto Peças'),
  ('Automotivo','Mecânica','AK Auto Center')
)
select csv.categoria, csv.subcategoria, csv.nome
from csv_iniciais csv
where not exists (
  select 1
  from candidatos c
  join subcategorias s on s.id = c.subcategoria_id
  join categorias cat on cat.id = s.categoria_id
  where lower(trim(c.nome)) = lower(trim(csv.nome))
    and lower(trim(s.nome)) = lower(trim(csv.subcategoria))
    and lower(trim(cat.nome)) = lower(trim(csv.categoria))
);


-- ==========================================================================
-- Q4 — DELETE de verdade (rode SÓ depois de validar Q1/Q2/Q3)
-- Sugeridos e candidatos com voto NUNCA são tocados pelas cláusulas abaixo.
-- ==========================================================================
with csv_iniciais (categoria, subcategoria, nome) as (values
  ('Alimentação','Restaurante','Cariri Cabaña'),
  ('Alimentação','Restaurante','Terra Tupi'),
  ('Alimentação','Restaurante','Mangará'),
  ('Alimentação','Restaurante','Camarada Camarão'),
  ('Alimentação','Restaurante','Sal e Brasa'),
  ('Alimentação','Restaurante','Di Vino'),
  ('Alimentação','Restaurante','Carne de Sol do Ramiro'),
  ('Alimentação','Restaurante','Pitu com Pirão da Eliane'),
  ('Alimentação','Restaurante','Restaurante Sollo'),
  ('Alimentação','Restaurante','Porto Seaside'),
  ('Alimentação','Restaurante','Casa da Picanha'),
  ('Alimentação','Bar','Tarrafas'),
  ('Alimentação','Bar','Conversafiada'),
  ('Alimentação','Bar','Cantina Locatelli'),
  ('Alimentação','Bar','Passarela do Caranguejo'),
  ('Alimentação','Pizzaria','Santa Pizza'),
  ('Alimentação','Pizzaria','La Vecchia'),
  ('Alimentação','Pizzaria','Tarrafas'),
  ('Alimentação','Pizzaria','Conversafiada'),
  ('Alimentação','Pizzaria','Cantina Locatelli'),
  ('Alimentação','Hamburgueria','Rei do Hambúrguer'),
  ('Alimentação','Hamburgueria','La Brasa'),
  ('Alimentação','Hamburgueria','Original Gaúcho Burguer'),
  ('Alimentação','Hamburgueria','Hamburgueria Do Seu Zé'),
  ('Alimentação','Hamburgueria','The Sandwich'),
  ('Alimentação','Hamburgueria','Juca''s'),
  ('Alimentação','Hamburgueria','Sete Beijos'),
  ('Alimentação','Hamburgueria','Lion''s Burguer'),
  ('Alimentação','Hamburgueria','Oxente Hamburgueria'),
  ('Alimentação','Sushi','Japa Aju'),
  ('Alimentação','Sushi','Joy Sushi'),
  ('Alimentação','Sushi','New Hakata'),
  ('Alimentação','Acarajé','Acarajé do Marcelo'),
  ('Alimentação','Acarajé','Acarajé da Rita'),
  ('Alimentação','Acarajé','Rei do Acarajé Aju'),
  ('Alimentação','Acarajé','Ponto do Acarajé Coroa do Meio'),
  ('Alimentação','Padaria','Pães e Trigo'),
  ('Alimentação','Padaria','Regina Delicatessen'),
  ('Alimentação','Padaria','Pand''oro'),
  ('Alimentação','Padaria','Sorvepan'),
  ('Alimentação','Sorveteria','Castelo Branco'),
  ('Alimentação','Sorveteria','Il Sordo'),
  ('Alimentação','Sorveteria','Bonjour Gourmet'),
  ('Alimentação','Sorveteria','Trupe'),
  ('Alimentação','Sorveteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Feito a Grão'),
  ('Alimentação','Cafeteria','O Rei do Sorvete'),
  ('Alimentação','Cafeteria','Pand''oro'),
  ('Comércio','Loja de Roupas','Riachuelo'),
  ('Comércio','Loja de Roupas','C&A'),
  ('Comércio','Loja de Roupas','Renner'),
  ('Comércio','Loja de Roupas','Hering'),
  ('Comércio','Loja de Roupas','Aramis'),
  ('Comércio','Loja de Roupas','Damyller'),
  ('Comércio','Loja de Roupas','Les Lis Blanc'),
  ('Comércio','Loja de Roupas','Básico Chic Modas'),
  ('Comércio','Loja de Calçados','Arezzo'),
  ('Comércio','Loja de Calçados','Santa Lolla'),
  ('Comércio','Loja de Calçados','Schutz'),
  ('Comércio','Loja de Calçados','Paquetá'),
  ('Comércio','Ótica','Ótica Sunshine'),
  ('Comércio','Ótica','Super Ótica São José'),
  ('Comércio','Ótica','Óticas Kohls'),
  ('Comércio','Ótica','Ótica Sergipe'),
  ('Comércio','Ótica','Mercadão dos Óculos'),
  ('Comércio','Ótica','Óticas Pontual'),
  ('Comércio','Joalheria','Vivara'),
  ('Comércio','Joalheria','Joalheria Fontes'),
  ('Comércio','Joalheria','Karib Joias'),
  ('Comércio','Joalheria','Safira Jóias'),
  ('Comércio','Joalheria','Leonia Joias'),
  ('Comércio','Joalheria','Pandora'),
  ('Comércio','Farmácia','Pague Menos'),
  ('Comércio','Farmácia','Drogasil'),
  ('Comércio','Farmácia','Drogarias Pacheco'),
  ('Comércio','Farmácia','Ultrafarma'),
  ('Comércio','Supermercado','GBarbosa'),
  ('Comércio','Supermercado','Lojas Guanabara'),
  ('Comércio','Supermercado','Carrefour'),
  ('Comércio','Supermercado','Atacadão'),
  ('Comércio','Supermercado','Sam''s Club'),
  ('Comércio','Supermercado','Makro'),
  ('Comércio','Móveis','Lojas Guanabara'),
  ('Comércio','Móveis','Tok&Stok'),
  ('Comércio','Móveis','Etna'),
  ('Comércio','Decoração','Tok&Stok'),
  ('Comércio','Decoração','Etna'),
  ('Comércio','Decoração','Camicado'),
  ('Comércio','Eletrodomésticos','Lojas Guanabara'),
  ('Comércio','Eletrodomésticos','Magazine Luiza'),
  ('Comércio','Eletrodomésticos','Casas Bahia'),
  ('Comércio','Eletrodomésticos','Lojas Americanas'),
  ('Comércio','Celulares e acessórios','Magazine Luiza'),
  ('Comércio','Celulares e acessórios','Casas Bahia'),
  ('Comércio','Celulares e acessórios','Fast Shop'),
  ('Comércio','Informática','Magazine Luiza'),
  ('Comércio','Informática','Fast Shop'),
  ('Comércio','Informática','Kabum'),
  ('Comércio','Perfumarias','Essencial Perfumaria'),
  ('Comércio','Perfumarias','Lojão dos Cosméticos'),
  ('Comércio','Perfumarias','O Boticário'),
  ('Comércio','Perfumarias','Natura'),
  ('Comércio','Perfumarias','Sephora'),
  ('Comércio','Cosméticos','Essencial Perfumaria'),
  ('Comércio','Cosméticos','Lojão dos Cosméticos'),
  ('Comércio','Cosméticos','O Boticário'),
  ('Comércio','Cosméticos','Natura'),
  ('Comércio','Cama, mesa e banho','Lojas Imperador'),
  ('Comércio','Cama, mesa e banho','Demarque'),
  ('Comércio','Cama, mesa e banho','Sempre Viva'),
  ('Comércio','Cama, mesa e banho','Golfran Aracaju'),
  ('Comércio','Tecidos','Rei dos Tecidos'),
  ('Comércio','Armarinhos','Armarinho São José'),
  ('Comércio','Materiais de construção','Rede Oxente'),
  ('Comércio','Materiais de construção','Decora Construção'),
  ('Comércio','Materiais de construção','Edmundo Casa e Construção'),
  ('Serviços','Salão de Beleza','Lottus Saúde e Estética'),
  ('Serviços','Salão de Beleza','Aju Beauty Concept'),
  ('Serviços','Salão de Beleza','Maison Garcia'),
  ('Serviços','Salão de Beleza','EL Shamah'),
  ('Serviços','Barbearia','The Barbers'),
  ('Serviços','Barbearia','Maestro Barbearia'),
  ('Serviços','Barbearia','Castelo Barber Club'),
  ('Serviços','Barbearia','Aju Barber'),
  ('Serviços','Barbearia','Democrata Barber Club'),
  ('Serviços','Barbearia','Barbearia Dell Dú'),
  ('Serviços','Academia','Academia Total Fitness'),
  ('Serviços','Academia','Academia Força Física'),
  ('Serviços','Academia','Smith Academia'),
  ('Serviços','Academia','G3 Fit'),
  ('Serviços','Academia','Academia H2O Fitness'),
  ('Serviços','Academia','Academia Paulo Bedeu'),
  ('Serviços','Academia','Nossa Academia'),
  ('Serviços','Pet Shop','Cobasi'),
  ('Serviços','Pet Shop','Meupet'),
  ('Serviços','Pet Shop','PetMania'),
  ('Serviços','Pet Shop','Petville'),
  ('Serviços','Pet Shop','Univet'),
  ('Serviços','Organização de eventos','Wellington'),
  ('Serviços','Organização de eventos','Tina Delícias'),
  ('Serviços','Organização de eventos','Alex Max'),
  ('Serviços','Organização de eventos','Tânia Vasconcelos Buffet'),
  ('Serviços','Organização de eventos','Delícias na Brasa'),
  ('Serviços','Contabilidade e Consultoria','Zannix Brasil Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','MCE Menezes Contabilidade Empresarial'),
  ('Serviços','Contabilidade e Consultoria','ERPAC Contabilidade'),
  ('Serviços','Contabilidade e Consultoria','INTERCON Contadores'),
  ('Serviços','Escritórios e Coworking','NEOWORKING'),
  ('Serviços','Escritórios e Coworking','Conviva Coworking'),
  ('Serviços','Escritórios e Coworking','HUA Coworking'),
  ('Serviços','Escritórios e Coworking','Ecoworking'),
  ('Serviços','Escritórios e Coworking','Top 360 Coworking'),
  ('Serviços','Escritórios e Coworking','Portal Escritório Virtual'),
  ('Lazer e Entretenimento','Casa de Show','Salles Multieventos'),
  ('Lazer e Entretenimento','Casa de Show','705 Aracaju'),
  ('Lazer e Entretenimento','Casa de Show','Amsterdam'),
  ('Lazer e Entretenimento','Casa de Show','Emes Centro de Eventos'),
  ('Lazer e Entretenimento','Cinema','Cinemark'),
  ('Lazer e Entretenimento','Cinema','UCI Cinemas'),
  ('Lazer e Entretenimento','Buffets','Wellington'),
  ('Lazer e Entretenimento','Buffets','Tina Delícias'),
  ('Lazer e Entretenimento','Buffets','Alex Max'),
  ('Lazer e Entretenimento','Buffets','Tânia Vasconcelos Buffet'),
  ('Lazer e Entretenimento','Hotéis','Celi Hotel'),
  ('Lazer e Entretenimento','Hotéis','Aquarius Praia Hotel'),
  ('Lazer e Entretenimento','Hotéis','Real Praia Hotel'),
  ('Lazer e Entretenimento','Pousadas','Hotel Pousada do Sol'),
  ('Lazer e Entretenimento','Pousadas','Pousada Dos Caminhos'),
  ('Lazer e Entretenimento','Pousadas','Pousada Raio de Sol'),
  ('Lazer e Entretenimento','Receptivos turísticos','Farol Tur'),
  ('Lazer e Entretenimento','Receptivos turísticos','Oxente Turismo'),
  ('Lazer e Entretenimento','Receptivos turísticos','Valtur Aracaju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Edsontur Viagens'),
  ('Lazer e Entretenimento','Receptivos turísticos','Receptivo Aju'),
  ('Lazer e Entretenimento','Receptivos turísticos','Costa Nova Turismo'),
  ('Educação','Escolas','Colégio CCPA'),
  ('Educação','Escolas','Colégio Intellectus'),
  ('Educação','Escolas','Colégio Ômega'),
  ('Educação','Escolas','Colégio Pio Décimo'),
  ('Educação','Escolas','Colégio Salesiano Aracaju'),
  ('Educação','Escolas','Instituto Dom Fernando Gomes'),
  ('Educação','Idiomas','Cultura Inglesa'),
  ('Educação','Idiomas','CCAA'),
  ('Educação','Idiomas','Wizard'),
  ('Educação','Idiomas','Yázigi'),
  ('Educação','Cursos livres','SENAC'),
  ('Educação','Cursos livres','SENAI'),
  ('Educação','Cursos livres','Universidade Tiradentes (Unit)'),
  ('Educação','Cursos livres','Uninassau'),
  ('Educação','Cursos livres','FACAR'),
  ('Educação','Cursos livres','Estácio (UNESA)'),
  ('Imóveis e Construção','Construtora','Jotanunes'),
  ('Imóveis e Construção','Construtora','Construtora Impacto'),
  ('Imóveis e Construção','Construtora','Construtora União'),
  ('Imóveis e Construção','Construtora','Construtora KLB'),
  ('Imóveis e Construção','Construtora','Construtora Stanza'),
  ('Imóveis e Construção','Construtora','Construtora Santa Maria'),
  ('Imóveis e Construção','Construtora','GL Construtora'),
  ('Imóveis e Construção','Construtora','Construtora EMPE'),
  ('Imóveis e Construção','Imobiliária','Gonzalez Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Cohab Premium'),
  ('Imóveis e Construção','Imobiliária','Smart Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Felizola Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Valor Imobiliária'),
  ('Imóveis e Construção','Imobiliária','Monica Andrade Imóveis'),
  ('Saúde','Hospital','Hospital Primavera'),
  ('Saúde','Hospital','Hospital São Lucas'),
  ('Saúde','Hospital','Hospital Hapvida'),
  ('Saúde','Clínica Veterinária','Univet'),
  ('Saúde','Clínica Veterinária','Afetto'),
  ('Saúde','Clínica Veterinária','Clínica São Lázaro'),
  ('Saúde','Clínica Veterinária','Diagnovet'),
  ('Saúde','Clínica Veterinária','Toca dos Gatos'),
  ('Saúde','Clínica Veterinária','Mr. Zoo'),
  ('Saúde','Plano de Saúde','Hapvida'),
  ('Saúde','Plano de Saúde','Unimed Sergipe'),
  ('Saúde','Plano de Saúde','Bradesco Saúde'),
  ('Saúde','Plano de Saúde','Amil'),
  ('Saúde','Laboratório','Centro de Diagnóstico Unimed'),
  ('Saúde','Laboratório','Lamac'),
  ('Saúde','Laboratório','Solim Laboratórios'),
  ('Saúde','Laboratório','Santa Anna'),
  ('Automotivo','Concessionária','Serigy Veículos'),
  ('Automotivo','Concessionária','Samam Fiat'),
  ('Automotivo','Concessionária','Chevrolet Contorno'),
  ('Automotivo','Auto Peças','O Barateiro Auto Peças'),
  ('Automotivo','Auto Peças','Auto Peças Macedo'),
  ('Automotivo','Auto Peças','Auto Peças Cardoso'),
  ('Automotivo','Auto Peças','JS Peças'),
  ('Automotivo','Auto Peças','Silveira Auto Peças'),
  ('Automotivo','Mecânica','AK Auto Center')
)
delete from candidatos c
where c.origem = 'oficial'
  and not exists (
    select 1
    from csv_iniciais csv
    join subcategorias s
      on lower(trim(s.nome)) = lower(trim(csv.subcategoria))
    join categorias cat
      on cat.id = s.categoria_id
     and lower(trim(cat.nome)) = lower(trim(csv.categoria))
    where s.id = c.subcategoria_id
      and lower(trim(csv.nome)) = lower(trim(c.nome))
  )
  and not exists (
    select 1 from votos v where v.candidato_id = c.id
  );
