-- ==========================================================================
-- Repõe os candidatos do CSV inicial que estão faltando no banco.
-- Características:
--   • Idempotente: só insere o que ainda não existe (NOT EXISTS).
--   • Pula linhas cuja subcategoria/categoria não existe no banco
--     (a linha simplesmente não casa no JOIN — não dá erro).
--   • origem='oficial', status='aprovado'.
--   • nome_normalizado é calculado igual à função TS `normalizarNome`:
--       lower → remove acentos → trim → colapsa espaços.
--
-- Roda no SQL Editor do Supabase. Sem `begin`/`commit` porque é só um INSERT.
-- ==========================================================================

with iniciais (categoria, subcategoria, nome, descricao) as (values
  ('Alimentação','Restaurante','Cariri Cabaña','Cozinha nordestina contemporânea à beira-mar'),
  ('Alimentação','Restaurante','Terra Tupi','Cozinha contemporânea sofisticada'),
  ('Alimentação','Restaurante','Mangará','Cozinha nordestina autêntica'),
  ('Alimentação','Restaurante','Camarada Camarão','Especialista em pratos com camarão'),
  ('Alimentação','Restaurante','Sal e Brasa','Churrascaria com rodízio de carnes nobres'),
  ('Alimentação','Restaurante','Di Vino','Cozinha italiana com vinhos selecionados'),
  ('Alimentação','Restaurante','Carne de Sol do Ramiro','Tradicional carne de sol nordestina'),
  ('Alimentação','Restaurante','Pitu com Pirão da Eliane','Pratos regionais com pitus frescos'),
  ('Alimentação','Restaurante','Restaurante Sollo','Peixes carnes e risotos'),
  ('Alimentação','Restaurante','Porto Seaside','Buffet de frutos do mar e carnes grelhadas'),
  ('Alimentação','Restaurante','Casa da Picanha','Especialista em picanha grelhada'),
  ('Alimentação','Bar','Tarrafas','Bar e rodízio na Orla de Atalaia'),
  ('Alimentação','Bar','Conversafiada','Rodízio de pizza e petiscos'),
  ('Alimentação','Bar','Cantina Locatelli','Vinhos do Vale do São Francisco'),
  ('Alimentação','Bar','Passarela do Caranguejo','Polo gastronômico com música ao vivo'),
  ('Alimentação','Pizzaria','Santa Pizza','Pizzas artesanais variadas'),
  ('Alimentação','Pizzaria','La Vecchia','Italiana com pizzas e massas'),
  ('Alimentação','Pizzaria','Tarrafas','Rodízio de pizza na Atalaia'),
  ('Alimentação','Pizzaria','Conversafiada','Rodízio mais completo da cidade'),
  ('Alimentação','Pizzaria','Cantina Locatelli','Pizza com vinhos selecionados'),
  ('Alimentação','Hamburgueria','Rei do Hambúrguer','4.5 estrelas com 1286 avaliações'),
  ('Alimentação','Hamburgueria','La Brasa','Hambúrgueres premium na Atalaia'),
  ('Alimentação','Hamburgueria','Original Gaúcho Burguer','Hambúrgueres na Farolândia'),
  ('Alimentação','Hamburgueria','Hamburgueria Do Seu Zé','4.1 estrelas TripAdvisor'),
  ('Alimentação','Hamburgueria','The Sandwich','Mini burger rodízio'),
  ('Alimentação','Hamburgueria','Juca''s','Hambúrgueres gourmet'),
  ('Alimentação','Hamburgueria','Sete Beijos','Hambúrgueres em Aracaju'),
  ('Alimentação','Hamburgueria','Lion''s Burguer','Hamburgueria local'),
  ('Alimentação','Hamburgueria','Oxente Hamburgueria','Hamburgueria e petiscaria'),
  ('Alimentação','Sushi','Japa Aju','Primeiro com pizza de sushi em Aracaju'),
  ('Alimentação','Sushi','Joy Sushi','Sushi no pote hot dog e burger'),
  ('Alimentação','Sushi','New Hakata','Restaurante japonês tradicional'),
  ('Alimentação','Acarajé','Acarajé do Marcelo','4.6 estrelas Google'),
  ('Alimentação','Acarajé','Acarajé da Rita','Tradicional um dos melhores do estado'),
  ('Alimentação','Acarajé','Rei do Acarajé Aju','4.4 estrelas Restaurant Guru'),
  ('Alimentação','Acarajé','Ponto do Acarajé Coroa do Meio','Tradicional na Coroa do Meio'),
  ('Alimentação','Padaria','Pães e Trigo','Pães artesanais e doces'),
  ('Alimentação','Padaria','Regina Delicatessen','Há mais de 30 anos no Bairro Luzia'),
  ('Alimentação','Padaria','Pand''oro','Padaria tradicional'),
  ('Alimentação','Padaria','Sorvepan','Sorvetes e pães'),
  ('Alimentação','Sorveteria','Castelo Branco','Tradicional atrativo turístico de Aracaju'),
  ('Alimentação','Sorveteria','Il Sordo','Sorvetes artesanais por surdos'),
  ('Alimentação','Sorveteria','Bonjour Gourmet','Gelateria comparável às de SP'),
  ('Alimentação','Sorveteria','Trupe','Sorvetes 100% artesanais'),
  ('Alimentação','Sorveteria','O Rei do Sorvete','Sorveteria & Cafeteria'),
  ('Alimentação','Cafeteria','Feito a Grão','Café especial no Shopping Jardins'),
  ('Alimentação','Cafeteria','O Rei do Sorvete','Cafeteria com cafés artesanais'),
  ('Alimentação','Cafeteria','Pand''oro','Café e padaria'),
  ('Comércio','Loja de Roupas','Riachuelo','Moda completa no Shopping RioMar'),
  ('Comércio','Loja de Roupas','C&A','Moda no Shopping RioMar'),
  ('Comércio','Loja de Roupas','Renner','Moda no Shopping Jardins'),
  ('Comércio','Loja de Roupas','Hering','Moda no Shopping Jardins'),
  ('Comércio','Loja de Roupas','Aramis','Moda masculina sofisticada'),
  ('Comércio','Loja de Roupas','Damyller','Moda jovem'),
  ('Comércio','Loja de Roupas','Les Lis Blanc','Moda premium feminina (RioMar)'),
  ('Comércio','Loja de Roupas','Básico Chic Modas','Loja local de moda feminina'),
  ('Comércio','Loja de Calçados','Arezzo','Calçados femininos premium'),
  ('Comércio','Loja de Calçados','Santa Lolla','Calçados femininos'),
  ('Comércio','Loja de Calçados','Schutz','Calçados femininos premium'),
  ('Comércio','Loja de Calçados','Paquetá','Calçados e acessórios'),
  ('Comércio','Ótica','Ótica Sunshine','Ótica mais bem avaliada de Aracaju'),
  ('Comércio','Ótica','Super Ótica São José','Bem avaliada Google com 2 anos garantia'),
  ('Comércio','Ótica','Óticas Kohls','Mais bem avaliada nas redes sociais'),
  ('Comércio','Ótica','Ótica Sergipe','486+ clientes 5 estrelas Google'),
  ('Comércio','Ótica','Mercadão dos Óculos','Armações modernas e preço justo'),
  ('Comércio','Ótica','Óticas Pontual','Tradicional ótica de Aracaju'),
  ('Comércio','Joalheria','Vivara','Shopping Jardins joias e relógios'),
  ('Comércio','Joalheria','Joalheria Fontes','Ambiente luxo no Shopping Jardins'),
  ('Comércio','Joalheria','Karib Joias','Joias para revenda no Centro'),
  ('Comércio','Joalheria','Safira Jóias','Tradicional joalheria de Aracaju'),
  ('Comércio','Joalheria','Leonia Joias','Joias em ouro 18k e relógios'),
  ('Comércio','Joalheria','Pandora','Joias personalizadas'),
  ('Comércio','Farmácia','Pague Menos','Rede de farmácias'),
  ('Comércio','Farmácia','Drogasil','Rede de farmácias'),
  ('Comércio','Farmácia','Drogarias Pacheco','Rede de farmácias'),
  ('Comércio','Farmácia','Ultrafarma','Rede de farmácias'),
  ('Comércio','Supermercado','GBarbosa','Tradicional sergipano'),
  ('Comércio','Supermercado','Lojas Guanabara','Tradicional rede do Nordeste'),
  ('Comércio','Supermercado','Carrefour','Hipermercado'),
  ('Comércio','Supermercado','Atacadão','Atacarejo'),
  ('Comércio','Supermercado','Sam''s Club','Atacadista membership'),
  ('Comércio','Supermercado','Makro','Atacadista'),
  ('Comércio','Móveis','Lojas Guanabara','Móveis e eletrodomésticos'),
  ('Comércio','Móveis','Tok&Stok','Móveis e decoração'),
  ('Comércio','Móveis','Etna','Móveis e decoração'),
  ('Comércio','Decoração','Tok&Stok','Decoração e móveis'),
  ('Comércio','Decoração','Etna','Decoração e móveis'),
  ('Comércio','Decoração','Camicado','Casa e decoração'),
  ('Comércio','Eletrodomésticos','Lojas Guanabara','Tradicional rede'),
  ('Comércio','Eletrodomésticos','Magazine Luiza','Eletrônicos e eletros'),
  ('Comércio','Eletrodomésticos','Casas Bahia','Eletrônicos e eletros'),
  ('Comércio','Eletrodomésticos','Lojas Americanas','Variedades e eletros'),
  ('Comércio','Celulares e acessórios','Magazine Luiza','Celulares e eletrônicos'),
  ('Comércio','Celulares e acessórios','Casas Bahia','Celulares e eletrônicos'),
  ('Comércio','Celulares e acessórios','Fast Shop','Eletrônicos premium'),
  ('Comércio','Informática','Magazine Luiza','Informática e eletrônicos'),
  ('Comércio','Informática','Fast Shop','Informática premium'),
  ('Comércio','Informática','Kabum','Informática especializada'),
  ('Comércio','Perfumarias','Essencial Perfumaria','Principal perfumaria de Aracaju'),
  ('Comércio','Perfumarias','Lojão dos Cosméticos','Tradicional desde 1994'),
  ('Comércio','Perfumarias','O Boticário','Rede nacional'),
  ('Comércio','Perfumarias','Natura','Rede nacional cosméticos'),
  ('Comércio','Perfumarias','Sephora','Cosméticos premium'),
  ('Comércio','Cosméticos','Essencial Perfumaria','Cosméticos no Shopping Box'),
  ('Comércio','Cosméticos','Lojão dos Cosméticos','Tradicional no Centro'),
  ('Comércio','Cosméticos','O Boticário','Cosméticos nacionais'),
  ('Comércio','Cosméticos','Natura','Cosméticos brasileiros'),
  ('Comércio','Cama, mesa e banho','Lojas Imperador','Preços de fábrica em Aracaju'),
  ('Comércio','Cama, mesa e banho','Demarque','Edredons enxovais e decoração'),
  ('Comércio','Cama, mesa e banho','Sempre Viva','Bairro 13 de Julho'),
  ('Comércio','Cama, mesa e banho','Golfran Aracaju','Tradicional no Centro'),
  ('Comércio','Tecidos','Rei dos Tecidos','Tradicional loja de tecidos'),
  ('Comércio','Armarinhos','Armarinho São José','Aviamentos e armarinho'),
  ('Comércio','Materiais de construção','Rede Oxente','Cimento areia tijolos pisos'),
  ('Comércio','Materiais de construção','Decora Construção','Frete grátis acima de R$200 em Aracaju'),
  ('Comércio','Materiais de construção','Edmundo Casa e Construção','Materiais de construção'),
  ('Serviços','Salão de Beleza','Lottus Saúde e Estética','Salão multifuncional 13 de Julho'),
  ('Serviços','Salão de Beleza','Aju Beauty Concept','Conceito moderno de beleza'),
  ('Serviços','Salão de Beleza','Maison Garcia','Salão de beleza'),
  ('Serviços','Salão de Beleza','EL Shamah','Salão de beleza'),
  ('Serviços','Barbearia','The Barbers','Barbearia premium em Aracaju'),
  ('Serviços','Barbearia','Maestro Barbearia','5.0 estrelas com 39 avaliações'),
  ('Serviços','Barbearia','Castelo Barber Club','5.0 estrelas Google'),
  ('Serviços','Barbearia','Aju Barber','Sede moderna no bairro Garcia'),
  ('Serviços','Barbearia','Democrata Barber Club','Bar massagens e tatuagens'),
  ('Serviços','Barbearia','Barbearia Dell Dú','5.0 estrelas com 47 avaliações'),
  ('Serviços','Academia','Academia Total Fitness','4.9 estrelas Google'),
  ('Serviços','Academia','Academia Força Física','4.7 estrelas com 88+ avaliações'),
  ('Serviços','Academia','Smith Academia','4.8 estrelas Google'),
  ('Serviços','Academia','G3 Fit','Estúdio funcional 9.1'),
  ('Serviços','Academia','Academia H2O Fitness','4.6 estrelas Google'),
  ('Serviços','Academia','Academia Paulo Bedeu','100% sergipana'),
  ('Serviços','Academia','Nossa Academia','Pilates e reabilitação'),
  ('Serviços','Pet Shop','Cobasi','Pet shop e clínica no RioMar'),
  ('Serviços','Pet Shop','Meupet','Quase 10 anos de mercado'),
  ('Serviços','Pet Shop','PetMania','Atendimento veterinário e produtos'),
  ('Serviços','Pet Shop','Petville','Centro de estética e hotel pet'),
  ('Serviços','Pet Shop','Univet','Clínica e pet shop 24h'),
  ('Serviços','Organização de eventos','Wellington','4.8 estrelas Google'),
  ('Serviços','Organização de eventos','Tina Delícias','4.8 estrelas Google'),
  ('Serviços','Organização de eventos','Alex Max','5.0 estrelas Google'),
  ('Serviços','Organização de eventos','Tânia Vasconcelos Buffet','4.6 estrelas Google'),
  ('Serviços','Organização de eventos','Delícias na Brasa','Buffet de churrasco completo'),
  ('Serviços','Contabilidade e Consultoria','Zannix Brasil Contabilidade','Desde 2015 referência no setor'),
  ('Serviços','Contabilidade e Consultoria','MCE Menezes Contabilidade Empresarial','Tradicional escritório familiar'),
  ('Serviços','Contabilidade e Consultoria','ERPAC Contabilidade','Maior contabilidade pública de Aracaju'),
  ('Serviços','Contabilidade e Consultoria','INTERCON Contadores','Top 3 maiores de Aracaju'),
  ('Serviços','Escritórios e Coworking','NEOWORKING','Primeiro coworking de Aracaju (2012)'),
  ('Serviços','Escritórios e Coworking','Conviva Coworking','Salas privativas e auditório'),
  ('Serviços','Escritórios e Coworking','HUA Coworking','Espaço compartilhado e escritório virtual'),
  ('Serviços','Escritórios e Coworking','Ecoworking','Coworking no bairro Jardins'),
  ('Serviços','Escritórios e Coworking','Top 360 Coworking','Coworking em Aracaju'),
  ('Serviços','Escritórios e Coworking','Portal Escritório Virtual','Primeiro com ISO 9001 do Brasil'),
  ('Lazer e Entretenimento','Casa de Show','Salles Multieventos','Capacidade para 15.000 pessoas'),
  ('Lazer e Entretenimento','Casa de Show','705 Aracaju','Casa de shows e eventos'),
  ('Lazer e Entretenimento','Casa de Show','Amsterdam','Casa de eventos com 3 ambientes'),
  ('Lazer e Entretenimento','Casa de Show','Emes Centro de Eventos','Capacidade para 5.500 pessoas'),
  ('Lazer e Entretenimento','Cinema','Cinemark','Shopping Jardins'),
  ('Lazer e Entretenimento','Cinema','UCI Cinemas','Shopping RioMar'),
  ('Lazer e Entretenimento','Buffets','Wellington','4.8 estrelas Google'),
  ('Lazer e Entretenimento','Buffets','Tina Delícias','4.8 estrelas Google'),
  ('Lazer e Entretenimento','Buffets','Alex Max','5.0 estrelas Google'),
  ('Lazer e Entretenimento','Buffets','Tânia Vasconcelos Buffet','4.6 estrelas Google'),
  ('Lazer e Entretenimento','Hotéis','Celi Hotel','Hotel cozy frente à praia'),
  ('Lazer e Entretenimento','Hotéis','Aquarius Praia Hotel','Hotel na Orla'),
  ('Lazer e Entretenimento','Hotéis','Real Praia Hotel','Hotel na Orla de Atalaia'),
  ('Lazer e Entretenimento','Pousadas','Hotel Pousada do Sol','Bem avaliado no Booking'),
  ('Lazer e Entretenimento','Pousadas','Pousada Dos Caminhos','Bom custo-benefício'),
  ('Lazer e Entretenimento','Pousadas','Pousada Raio de Sol','Piscina e estrutura completa'),
  ('Lazer e Entretenimento','Receptivos turísticos','Farol Tur','99.8% avaliações positivas'),
  ('Lazer e Entretenimento','Receptivos turísticos','Oxente Turismo','Cânions Xingó e Lagoa do Tambaqui'),
  ('Lazer e Entretenimento','Receptivos turísticos','Valtur Aracaju','Passeios bem organizados'),
  ('Lazer e Entretenimento','Receptivos turísticos','Edsontur Viagens','Pacotes turísticos'),
  ('Lazer e Entretenimento','Receptivos turísticos','Receptivo Aju','Atendimento atencioso'),
  ('Lazer e Entretenimento','Receptivos turísticos','Costa Nova Turismo','Guias bem informados'),
  ('Educação','Escolas','Colégio CCPA','46 anos de tradição em Aracaju'),
  ('Educação','Escolas','Colégio Intellectus','Referência em educação'),
  ('Educação','Escolas','Colégio Ômega','Bairro Santos Dumont'),
  ('Educação','Escolas','Colégio Pio Décimo','Centro de Aracaju'),
  ('Educação','Escolas','Colégio Salesiano Aracaju','Tradicional ensino salesiano'),
  ('Educação','Escolas','Instituto Dom Fernando Gomes','Bairro Dezoito do Forte'),
  ('Educação','Idiomas','Cultura Inglesa','Inglês com tradição'),
  ('Educação','Idiomas','CCAA','Inglês e espanhol'),
  ('Educação','Idiomas','Wizard','Idiomas para todas as idades'),
  ('Educação','Idiomas','Yázigi','Inglês e outras línguas'),
  ('Educação','Cursos livres','SENAC','Cursos profissionalizantes'),
  ('Educação','Cursos livres','SENAI','Cursos técnicos e industriais'),
  ('Educação','Cursos livres','Universidade Tiradentes (Unit)','Primeira universidade particular de SE'),
  ('Educação','Cursos livres','Uninassau','Centro Universitário Maurício de Nassau'),
  ('Educação','Cursos livres','FACAR','Faculdade de Aracaju desde 2001'),
  ('Educação','Cursos livres','Estácio (UNESA)','Universidade Estácio de Sá em Aracaju'),
  ('Imóveis e Construção','Construtora','Jotanunes','Top 3 de Aracaju'),
  ('Imóveis e Construção','Construtora','Construtora Impacto','40 anos no mercado sergipano'),
  ('Imóveis e Construção','Construtora','Construtora União','Top 100 do Brasil'),
  ('Imóveis e Construção','Construtora','Construtora KLB','Empreendimentos em Aracaju'),
  ('Imóveis e Construção','Construtora','Construtora Stanza','Apartamentos na planta'),
  ('Imóveis e Construção','Construtora','Construtora Santa Maria','Construções em Aracaju'),
  ('Imóveis e Construção','Construtora','GL Construtora','Empreendimentos imobiliários'),
  ('Imóveis e Construção','Construtora','Construtora EMPE','Apartamentos em Aracaju'),
  ('Imóveis e Construção','Imobiliária','Gonzalez Imobiliária','Tradicional em Aracaju e Sergipe'),
  ('Imóveis e Construção','Imobiliária','Cohab Premium','Desde 1993 no mercado sergipano'),
  ('Imóveis e Construção','Imobiliária','Smart Imobiliária','Compra venda e aluguel'),
  ('Imóveis e Construção','Imobiliária','Felizola Imobiliária','Imóveis em Aracaju'),
  ('Imóveis e Construção','Imobiliária','Valor Imobiliária','Tradicional em Aracaju'),
  ('Imóveis e Construção','Imobiliária','Monica Andrade Imóveis','Bairro Jardins'),
  ('Saúde','Hospital','Hospital Primavera','Tecnologia de ponta na Rede Primavera'),
  ('Saúde','Hospital','Hospital São Lucas','Desde 1969 referência em cardiologia'),
  ('Saúde','Hospital','Hospital Hapvida','Cobertura completa em Sergipe'),
  ('Saúde','Clínica Veterinária','Univet','Clínica veterinária 24h'),
  ('Saúde','Clínica Veterinária','Afetto','Clínica com laboratório próprio'),
  ('Saúde','Clínica Veterinária','Clínica São Lázaro','Estrutura completa na Farolândia'),
  ('Saúde','Clínica Veterinária','Diagnovet','Clínica pet shop e laboratório'),
  ('Saúde','Clínica Veterinária','Toca dos Gatos','Especializada em felinos'),
  ('Saúde','Clínica Veterinária','Mr. Zoo','Clínica veterinária e pet shop'),
  ('Saúde','Plano de Saúde','Hapvida','Cobertura ambulatorial e hospitalar'),
  ('Saúde','Plano de Saúde','Unimed Sergipe','Cooperativa médica tradicional'),
  ('Saúde','Plano de Saúde','Bradesco Saúde','Plano nacional'),
  ('Saúde','Plano de Saúde','Amil','Plano nacional'),
  ('Saúde','Laboratório','Centro de Diagnóstico Unimed','Análises clínicas e exames'),
  ('Saúde','Laboratório','Lamac','40 anos cuidando de você'),
  ('Saúde','Laboratório','Solim Laboratórios','Aceita diversos planos'),
  ('Saúde','Laboratório','Santa Anna','Análises clínicas'),
  ('Automotivo','Concessionária','Serigy Veículos','Concessionária Honda'),
  ('Automotivo','Concessionária','Samam Fiat','Concessionária Fiat'),
  ('Automotivo','Concessionária','Chevrolet Contorno','Concessionária Chevrolet'),
  ('Automotivo','Auto Peças','O Barateiro Auto Peças','Tradição em peças automotivas'),
  ('Automotivo','Auto Peças','Auto Peças Macedo','Desde 1980 em Aracaju'),
  ('Automotivo','Auto Peças','Auto Peças Cardoso','Mais de 30 anos no mercado'),
  ('Automotivo','Auto Peças','JS Peças','Filial em Aracaju'),
  ('Automotivo','Auto Peças','Silveira Auto Peças','Tradicional em Aracaju'),
  ('Automotivo','Mecânica','AK Auto Center','Multimarcas desde 2005, 4.8 estrelas')
)
insert into candidatos (subcategoria_id, nome, nome_normalizado, descricao, origem, status)
select
  s.id,
  i.nome,
  -- nome_normalizado: lower + remove acentos + colapsa espaços (igual TS)
  regexp_replace(
    lower(translate(trim(i.nome),
      'ÁÀÂÃÄÅáàâãäåÉÈÊËéèêëÍÌÎÏíìîïÓÒÔÕÖóòôõöÚÙÛÜúùûüÇçÑñ',
      'AAAAAAaaaaaaEEEEeeeeIIIIiiiiOOOOOoooooUUUUuuuuCcNn')),
    '\s+', ' ', 'g'
  ),
  i.descricao,
  'oficial',
  'aprovado'
from iniciais i
join subcategorias s
  on lower(trim(s.nome)) = lower(trim(i.subcategoria))
join categorias cat
  on cat.id = s.categoria_id
 and lower(trim(cat.nome)) = lower(trim(i.categoria))
where not exists (
  select 1 from candidatos c
  where c.subcategoria_id = s.id
    and lower(trim(c.nome)) = lower(trim(i.nome))
);

-- Resumo final
select
  (select count(*) from candidatos)                              as total_candidatos,
  (select count(*) from candidatos where origem = 'oficial')      as oficiais,
  (select count(*) from candidatos where origem = 'sugerido')     as sugeridos;
